export default {
  ADD_EVENT: 'Add Event',
  ADD_VENUE: 'Add Venue',
  CONFIRM_EMAIL: 'Confirm Email',
  EVENT_OPTIONS: 'Event Options',
  EDIT_EVENT: 'Edit Event',
  EDIT_VENUE: 'Edit Venue',
  FORGOT_PASSWORD: 'Forgot Password',
  HOME: 'Home',
  HOME_ORGANISER: 'Home Organiser',
  HOME_STAFF: 'Home Staff',
  INVITE_STAFF: 'Invite Staff',
  LANDING_PAGE: 'Landing Page',
  LOGIN: 'Login',
  LOGIN_STAFF: 'Login Staff',
  LOGIN_ORGANISER: 'Login Organiser',
  PREVIEW_EVENT: 'Preview Event',
  PROFILE: 'Profile',
  RESET_PASSWORD: 'Reset Password',
  // SCAN_QR_STAFF: 'Scan Staff QR',
  SCAN_TICKET: 'Scan Ticket',
  VALID_TICKET: 'Verified',
  // VENUE_INFO: 'venue',
};
